### ISSUE TITLE
ImportError: cannot import name 'prefetch_to_device'

### ISSUE THREAD

**Issue by c1a1o1** [taki0112/Self-Attention-GAN-Tensorflow#1]
WARNING:tensorflow:From E:\Users\Raytine\Anaconda3\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
Using TensorFlow backend.
Traceback (most recent call last):
  File "F:/Image-Forgery/niubiSelf-Attention-GAN-Tensorflow-master (1)/Self-Attention-GAN-Tensorflow-master/main.py", line 1, in <module>
    from SAGAN import SAGAN
  File "F:\Image-Forgery\niubiSelf-Attention-GAN-Tensorflow-master (1)\Self-Attention-GAN-Tensorflow-master\SAGAN.py", line 4, in <module>
    from tensorflow.contrib.data import prefetch_to_device, shuffle_and_repeat, map_and_batch
ImportError: cannot import name 'prefetch_to_device'

**Comment by taki0112** [comment]
what is your tensorflow version ?

**Comment by c1a1o1** [comment]
1.7  I update it soon！Thank you !
